### PR TITLE
Add github authentication route

### PR DESCRIPTION
**Pull request by Mubangizi**
# Description
Adds endpoint for GitHub authentication

## Trello Ticket ID

Click [here](https://trello.com/c/TCOm5uys/763-github-authentication-integration-with-cc-harbor) for a link to the Trello ticket

## How Can This Be Tested?

Add the code in the body of `POST` method on route `/users/oauth`

### CODE REVIEW

**Review by ttcollins — COMMENTED** [review]
How do we retrieve the code to use in the body of the post? I don't seem to have a specific code to use for the test

**Review by MutegekiHenry — APPROVED** [review]
Good work on this @Mubangizi

**Review by neelxie — APPROVED** [review]
good stuff

**Review by ttcollins — APPROVED** [review]
Good work @Mubangizi

**Pull request merged**
