### PR TITLE
feat: monitor cluster stats

### PR DESCRIPTION
**Pull request by MutegekiHenry**
# Description

This PR creates a route on which to access stats about clusters `clusters/stats`

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Trello Ticket ID

https://trello.com/c/rKb7IjKn

## How Can This Be Tested?

Pull this branch locally, navigate to API docs to the route `/clusters/stats`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Mubangizi** [comment]
Hey @MutegekiHenry , just wondering; You created an endpoint for cluster stats and your only showing `cluster count`? Is some data lucking

**Comment by MutegekiHenry** [comment]
> Hey @MutegekiHenry , just wondering; You created an endpoint for cluster stats and your only showing `cluster count`? Is some data lucking

Ideally, as more stats come in, they are to be added to this endpoint. For now this is all that the info I could monitor based on feedback from the team. But you could suggest more details that could be added

**Comment by Mubangizi** [comment]
> > Hey @MutegekiHenry , just wondering; You created an endpoint for cluster stats and your only showing `cluster count`? Is some data lucking
> 
> Ideally, as more stats come in, they are to be added to this endpoint. For now this is all that the info I could monitor based on feedback from the team. But you could suggest more details that could be added

I cant think of any the moment, because all i know is that we have cluster dependent stats for monitoring already. am just not sure about what this is for.
When do you even need cluster count. i feel this should wait till it actually ready to be used, just saying

**Comment by MutegekiHenry** [comment]
> > > Hey @MutegekiHenry , just wondering; You created an endpoint for cluster stats and your only showing `cluster count`? Is some data lucking
> > 
> > 
> > Ideally, as more stats come in, they are to be added to this endpoint. For now this is all that the info I could monitor based on feedback from the team. But you could suggest more details that could be added
> 
> I cant think of any the moment, because all i know is that we have cluster dependent stats for monitoring already. am just not sure about what this is for.
> When do you even need cluster count. i feel this should wait till it actually ready to be used, just saying

It's basically looking at the general overview of clusters, now that we are soon moving into multi cluster, admin might need to have this summary information, together with details on cluster location. So having this will be a basis to build on.

**Comment by MutegekiHenry** [comment]
Let me move this to the existing `/clusters` endpoint as @Mubangizi suggests

**Pull request closed without merging**
