### PR TITLE
Feat: Add date created timestamp to metrics response

### PR DESCRIPTION
**Pull request by Mubangizi**
#### What this PR does
-  Adds Project and app date created `timestamp` to app metrics
-  Adds `date_created` field to `app` and `project models`

### CODE REVIEW

**Review by MutegekiHenry — COMMENTED** [review]
@Mubangizi I notice that this PR appends a date created of a certain resource to the metrics endpoints, although i though this should be appended to the endpoints that return the actual resources.

**Comment by Mubangizi** [comment]
Men this is confusing, I think we should have a discussion about this with front-end...
What do you say?

**Comment by Mubangizi** [comment]
Okay @MutegekiHenry I have added date created to the ap and project schemas too

**Review by MutegekiHenry — APPROVED** [review]
Thanks @Mubangizi

**Review by inno-asiimwe — APPROVED** [review]
LGTM

**Pull request merged**
