### PR TITLE
Check and validate flutter-wave payment status

### PR DESCRIPTION
**Pull request by e-ian**
# Description

- Validate the payment status whether successful or not.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Trello Ticket ID

- https://trello.com/c/vTy3FIxq

## How Can This Be Tested?

- Fetch the branch and test the get request using the transaction_id of the transaction whose status you want to verify in the query params.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by MutegekiHenry** [comment]
@e-ian some tests are failing, kindly look into it

**Comment by e-ian** [comment]
> @e-ian some tests are failing, kindly look into it

@MutegekiHenry this has since been resolved

**Review by bashaashma — DISMISSED** [review]
Looks good to me.

**Review by MutegekiHenry — APPROVED** [review]
LGTM

**Review by bashaashma — APPROVED** [review]
Looks good to me

**Pull request merged**
