### PR TITLE
Ft refactor invoice email

### PR DESCRIPTION
**Pull request by Awath-Abdat**
# Description

Added content to the invoice mail template telling users to visit their dashboard so that they can access a PDF version of their invoice. Also formatted the table to have more padding between columns for better readability of the table.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

Please add a link to the Trello ticket for the task.

https://trello.com/c/bxiqOMo8

## How Can This Be Tested?

This can be tested by using the invoice api endpoint in the apidocs. An invoice email is sent to the project owner where the table showing the project details is shown and instructions for the owner to click on the 'Visit Dashboard' button to access his or her dashboard and get the PDF document of the invoice.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
Opera Snapshot_2022-06-21_194935_mail google com

### CODE REVIEW

**Comment by Mubangizi** [comment]
Hey @Awath-Abdat this is great work, but please change the base branch from `master` to `develop-new`
Screenshot from 2022-06-22 03-06-20

**Comment by Awath-Abdat** [comment]
Okay noted, thought had changed that before i pushed

**Comment by MutegekiHenry** [comment]
> Okay noted, thought had changed that before i pushed
> […](#)

I think Allan meant the base branch at the point of raising the PR. I rectified it.

**Review by Mubangizi — APPROVED** [review]
Great work @Awath-Abdat

**Review by MutegekiHenry — APPROVED** [review]

**Pull request merged**
