### PR TITLE
update query parameters for inactive user's endpoint

### PR DESCRIPTION
**Pull request by jnsereko**
# Description

added the start and end date query parameter for `"/users/inactive_users":`

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Can This Be Tested?

navigate to `http://127.0.0.1:5000/apidocs/#/users/get_users_inactive_users`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jnsereko** [comment]
Screenshot 2023-06-25 at 00 04 58

**Comment by inno-asiimwe** [comment]
Unrelated to this PR, but I believe that we did not need to have a separate endpoint to list active and inactive users. Instead we should have added a `status` query param to `/users` to filter out inactive or active users.  We do not need to do anything at the moment just thought I should mention it here. cc @Mubangizi @MutegekiHenry

**Review by inno-asiimwe — APPROVED** [review]

**Comment by jnsereko** [comment]
> Unrelated to this PR, but I believe that we did not need to have a separate endpoint to list active and inactive users. Instead we should have added a `status` query param to `/users` to filter out inactive or active users. We do not need to do anything at the moment just thought I should mention it here. cc @Mubangizi @MutegekiHenry

1+ from me on this.  However, this means that the `/users` endpoint would have to define optional `start` and. `end` date which logically complicates implementation at a significant level.

**Comment by inno-asiimwe** [comment]
> > Unrelated to this PR, but I believe that we did not need to have a separate endpoint to list active and inactive users. Instead we should have added a `status` query param to `/users` to filter out inactive or active users. We do not need to do anything at the moment just thought I should mention it here. cc @Mubangizi @MutegekiHenry
> 
> 1+ from me on this. However, this means that the `/users` endpoint would have to define optional `start` and `end` date which logically complicates implementation by a significant percentage.
> 
> ie I am seeing alot of `if` statements here.
> 
> * `if status is defined` get its parameter
> * `if start and end date is not defined but status is defined`, throw and argument error
> * `if the rest of the arguments are empty`, then return the all users,
> * ....

Aah, you would have to approach it differently, take the url params and pass them to all the way down to the db query. Define  meaningful defaults. that way you won't have a lot ifs in the controller. Feel free to setup sometime for a call in case we need to discuss this more. Though not to block the rest of the work, I would advise that you go ahead and get this merged in as is and if need be, create a new ticket for the refactor of that functionality.

**Comment by jnsereko** [comment]
following this up from https://trello.com/c/tLMxBtKx/1541-migrate-inactive-users-to-users-endpoint

**Pull request merged**
