### PR TITLE
Add trailing Invoice notifications

### PR DESCRIPTION
**Pull request by Mubangizi**
# Description
Creates a route that the admin can trigger email notifications to all users with uncashed invoices of over 30 days

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Can This Be Tested?

Go to `/invoices/notify`

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by MutegekiHenry** [comment]
Great work @Mubangizi the logic looks good. One question, how do you envision this route being triggered? Is it by an admin and how often? Is it by a cron job ? if cron how will you handle authentication

**Comment by e-ian** [comment]
@Mubangizi, please resolve conflicts and address given comments

**Comment by Mubangizi** [comment]
> Great work @Mubangizi the logic looks good. One question, how do you envision this route being triggered? Is it by an admin and how often? Is it by a cron job ? if cron how will you handle authentication

I built this for the admin, then we can build for the clone job if its being implemented, and handle those security measures for it

**Review by MutegekiHenry — APPROVED** [review]
LGMT

**Pull request merged**
