### PR TITLE
Add database sizes

### PR DESCRIPTION
**Pull request by Mubangizi**
#### What this PR does
- Adds a function to return database size
- Can be tested by checking out the detail database view of `GET` method at `/projects/{projectID}/databases/{databaseID}`

### CODE REVIEW

**Comment by ttcollins** [comment]
image

**Review by ttcollins — APPROVED** [review]
image
Worked fine with my newly created db. Someone could test using a db with data

**Review by ttcollins — APPROVED** [review]

**Review by Masozera — APPROVED** [review]
Well done!

**Review by neelxie — APPROVED** [review]

**Review by MutegekiHenry — APPROVED** [review]
Works as expected. Kudos @Mubangizi Though i did get to test with a db having some data

**Pull request merged**
