### PR TITLE
Create db_flavour integration

### PR DESCRIPTION
**Pull request by Mubangizi**
#### What this PR does
- Adds `DatabaseFlavour` model to the database
- Creates CRUD for `DatabaseFalvour` model
- Refactor controller for `project_database` 
       - To integrate `database_flavour` as a parent
       - To make database service classes dependent on what `database flavour` is attached to the `project_database` 
       - Works well with both MySQL and Postgres
#### How it can be tested

1. Pull and run the branch locally
2. Run migrations upgrade against your database to add new database flavor model
3. Create two `database_flavour` records and call them `mysql` and `postgres` (please mind the casing)
4. Now you can create a database with `POST` on one of these routes `/project_databases/<project_id>` or `/databases` by passing one of your flavours to the body.

### CODE REVIEW

**Review by MutegekiHenry — APPROVED** [review]
looks good, thanks @Mubangizi

**Review by inno-asiimwe — CHANGES_REQUESTED** [review]
Great work @Mubangizi , for the schema, we should be able to validate that the string is one of `mysql` or `postgres`.

**Comment by Mubangizi** [comment]
> Great work @Mubangizi , for the schema, we should be able to validate that the string is one of `mysql` or `postgres`.

@inno-asiimwe, this has been worked on. thank you for the feednback

**Review by inno-asiimwe — APPROVED** [review]
LGTM

**Pull request merged**
