### PR TITLE
Making projects private or public

### PR DESCRIPTION
**Pull request by LanternNassi**
# Description

This is to make projects public or private 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Trello Ticket ID

https://app.clickup.com/t/869515w0j

### CODE REVIEW

**Review by Mubangizi — COMMENTED** [review]
This is great @LanternNassi, please also limit private projects from being seen in `activity feed` by other users.

**Review by Mubangizi — COMMENTED** [review]
Also a small thing, please add the `is_public` field in the `api_docs.yml` file

**Comment by LanternNassi** [comment]
> Also a small thing, please add the `is_public` field in the `api_docs.yml` file

This is there @Mubangizi

**Comment by Mubangizi** [comment]
> > Also a small thing, please add the `is_public` field in the `api_docs.yml` file
> 
> This is there @Mubangizi

Not really, please check and verify in the file

**Review by Mubangizi — APPROVED** [review]

**Pull request merged**
