### PR TITLE
Ready for Production

### PR DESCRIPTION
**Pull request by inno-asiimwe**
# Description

Please include a summary of what the PR does adding relevant information, motivation and context.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Trello Ticket ID

Please add a link to the Trello ticket for the task.

## How Can This Be Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test scenario/configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by inno-asiimwe** [comment]
@e-ian could we have someone look at the conflicts between master and develop-new. We are making the situation worse by merging more work into develop-new.

**Comment by e-ian** [comment]
> @e-ian could we have someone look at the conflicts between master and develop-new. We are making the situation worse by merging more work into develop-new.

Let me take a look at that!

**Comment by e-ian** [comment]
@inno-asiimwe conflicts have been resolved.

**Comment by Mubangizi** [comment]
> @inno-asiimwe conflicts have been resolved.
Nice

**Pull request merged**
